### ISSUE TITLE
Connect High Level Rubric with Topic Rubric

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#10]
# Summary

This is a detailing of the relation between issues [#86](https://github.com/FOSSRIT/tasks/issues/86) and [#96](https://github.com/FOSSRIT/tasks/issues/96).  

# Background

The High Level Rubric needs access to higher detail from the topics listed for each team. This issue explains how this will be done.

# Details

- Get issues [#86](https://github.com/FOSSRIT/tasks/issues/86) and [#96](https://github.com/FOSSRIT/tasks/issues/96) done in their own right.
- Send the rubrics to the teams
- Once the teams start self-evaluating we will start to inform the High Level Rubric, factoring in our own evaluations as well.
- We link to the topic rubrics from the high level rubric

# Outcome

We will have an easy-to-access overview of the team's progress as well as an easy way to get more detailed information.

---

_Migrated from FOSSRIT/tasks#97._

**Comment by justwheel** [comment]
@whenbellstoll Is anything new here [since June](https://github.com/FOSSRIT/tasks/issues/97#issuecomment-500586198) or are the team rubrics still unlinked from the high-level rubric?

**Comment by Nolski** [comment]
I think our rubrics are essentially one file now so I'm going to close this ticket.
