### ISSUE TITLE
Create Template for Milestones

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#13]
[**>>> Working Draft of Template <<<**](https://docs.google.com/document/d/1M2nVwh7ArjAU31M7QZWP4AQz1cOyMhw90iP8Wg9lZNo/edit?usp=sharing)
# Summary

Create a draft template to use when delivering Milestone plans for our companies

# Background

Our companies need a detailed plan of action when it comes to developing their FOSS strategy. This milestone tracker will have specific points of actions, deliverables, and resources needed to progress from one step to the next.

# Outcome

A finished milestone tracker template

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

This is complete. A public version exists in the Resources site (https://librecorps.github.io/resources/ai/milestone-roadmap/) but the parent template currently lives in our Shared Drive. Eventually, I hope that it will move to the _Resources_ site.

Closing as complete. :clapper:
