### ISSUE TITLE
Create Mission Statement Guide

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#14]
[**>>> Link to Guide <<<**](https://docs.google.com/document/d/1APbBrGnijuECXvTjNOKAXhOsBJ17pJ91s0ct5tmEZrc/edit?usp=sharing)

## Overview

We want to create a comprehensive guide on developing a FOSS mission statement using the best resources out there on making these decisions in a way that's transparent and inclusive

## Output

Mission statement document

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

This is done and exists in our Shared Drive. Also hoping to move this content publicly in the foreseeable future. Closing as complete. :clapper:
