### ISSUE TITLE
Create presentation outline for MozFest + LibreCorps 

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#19]
# Summary

Create first draft of presentation/session outline for LibreCorps MozFest 2019 session

# Background

Earlier this year, we applied to run an interactive session at Mozilla Festival 2019 with our LibreCorps resources and assets. The session was recently accepted. Now, we need to begin planning the session and coming up with an interactive format to include a live audience in using our resources.

# Details

For now, a first step is to organize details into a document outline. Then I can collect some feedback from others and begin building out further steps to improve on what we present there at MozFest.

# Outcome

Initial path forward on what we take to MozFest 2019

**Comment by Nolski** [comment]
Link to session proposal: https://docs.google.com/document/d/1CVOn6UkRRQ_UD2fp9_gvf0_EUHXPCw-9VgLN0S52zJ0/edit?usp=sharing

Based on our proposal, we have our presentation broken out into 3 main components.

### Introduce attendees to LibeCorps "framework"

This includes:

 - Our milestone template
 - Our FOSS grading rubric
 - What else?

### Build out a roadmap/rubric for an existing project

Which project do we want to use?

### Break into groups and attendees will develop their own roadmap/rubric

How do we want to emphasize the rubric over the roadmap? How can we simplify this down into the most concise manner?

**Comment by Nolski** [comment]
Link to session outline: https://docs.google.com/document/d/1LcJ0I5O1zt_TGiXpiXnoX7YhrUT7roCt9bbm8ulfvQM/edit?usp=sharing

**Comment by justwheel** [comment]
I'm planning to throw an outline with some slides together by Monday. We're checking in again via BlueJeans on October 2nd.

**Comment by Nolski** [comment]
MozFest presentation happened. Great job @jwflory!
