### ISSUE TITLE
Update UNICEF Milestone Plans with Testing & CI Resources

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#2]
# Summary

UNICEF would prefer our milestone guides specifically mention testing and CI in their milestone plan

# Outcome

Updated milestone guides with testing & CI integrated

**Comment by Nolski** [comment]
@whenbellstoll I've added a few good resources on CI and unit testing. I think in general we should give them a few resources for getting started on testing in Milestone 1 and then follow up with some more resources if they're having trouble achieving code coverage in Milestone 2. I also think we should leave the CI stuff for milestone 2 as well. Any thoughts?

We will likely need to tailor the testing stuff depending on the technology as testing a blockchain app is very different from testing a VR application.

**Comment by whenbellstoll** [comment]
@Nolski For resources on CI I think you're right on the money, introduce the concept early and have supplementary materials at milestone 2. I would stretch the CI goals across Milestone 2 and 3, with Milestone 2 acting as an establishment of CI and Milestone 3 being its complete implementation (or as complete as UNICEF requires, 80 percent).

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

The current milestone roadmaps include testing and continuous integration resources. This content currently lives on the Shared Drive for FOSS@MAGIC. Eventually, I hope to port it out to the _Resources_ site.

Closing as complete. :clapper:
