### ISSUE TITLE
Write abstract/description for BoF session at FOSDEM 2020 by 11 Oct

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#20]
# Summary

Write abstract and description for [Birds of a Feather](https://en.wikipedia.org/wiki/Birds_of_a_feather_(computing)) (BoF) session about transparent/ethical evaluations of AI in FOSDEM 2020 before 11 October CFP deadline

# Background

@Nolski and I discussed the idea of splitting up into two sessions about a week ago.

A FOSDEM 2020 main track session gives our ideas on AI transparency and ethics a platform, but it is mostly unidirectional, i.e. we are talking to an audience. To better support our overall mission, combining the main track proposal **with** a ≥60 minutes BoF session affords us bidirectional conversations with others at FOSDEM.

We also reach two different audiences: the main track session gives a general overview of our ideas for anyone, and the BoF session offers a deeper dive on AI transparency/ethics for those with deeper background and interest.

# Details

Need to write abstract and description _**before 11 October CFP deadline**_.

In another issue, we can discuss a roadmap of how to facilitate the session and best engage a crowd of people with our ideas (maybe taking a page or two out of our MozFest facilitator handbook). But I figure it is best to wait for CFP status updates before investing too much time into planning an open-ended BoF session.

# Outcome

* Obtain unique and helpful feedback on our ideas from a wider community
* Empower others to become leaders within their own organizations for more ethical and transparent ways to develop AI systems

---

**cc**: @itprofjacobs

**Comment by Nolski** [comment]
CFP has been submitted to FOSDEM
