### ISSUE TITLE
Invite SJ to LibreCorps GitHub org, help him set up notifications

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#21]
# Summary

Help add SJ's GitHub account to this LibreCorps GitHub organization

# Background

SJ is not a member of this GH organization, probably should do some follow-up to get him here since he is not seeing any of this discussion.

# Details

1. Log in, navigate to github.com/librecorps
2. Accept invitation
3. Publish membership

# Outcome

SJ receives emails about new discussion / focus for GH task tracking / planning

**Comment by Nolski** [comment]
I believe that he's invited but you have to accept the invitation?

**Comment by justwheel** [comment]
Followed up on 2019-11-06.

**Comment by justwheel** [comment]
This was done in FOSS Hours today! Hi SJ! :wave:
