### ISSUE TITLE
Update UNICEF Contract & Guidance document

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#3]
# Summary

Integrate our [UNICEF Contract Guidance](https://docs.google.com/document/d/1pbFPuLurFuFnIMfaebseNLPAYroaQT69Nxdz_hwdNbE/edit) document with the UNICEF cohort document

# Outcome

Document suggestions inline sent to Meghan

**Comment by Nolski** [comment]
@whenbellstoll feel free to take a look through the updates I've made to the guidance document. The big adds I've made is having a public ticket tracker that's aligned with their product development tasks as well as adding a 6 week review to ensure they've released their code online open source.

**Comment by Nolski** [comment]
@whenbellstoll feel free to take a look through the updates I've made to the guidance document. The big adds I've made is having a public ticket tracker that's aligned with their product development tasks as well as adding a 6 week review to ensure they've released their code online open source.

**Comment by justwheel** [comment]
@Nolski Any updates on progress with UNICEF? I like what I see in the document.

**Comment by Nolski** [comment]
Edits have been suggested
