### ISSUE TITLE
Set up follow up calls with milestone plans

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#4]
# Summary

Set up walk through calls for UNICEF teams based on our new milestone planning documents

Blocked by #2 

# Outcome

Follow up calls based on our new milestone planning document

**Comment by Nolski** [comment]
I have officially reached out to all of the Gates Foundation teams as well as the Blockchain cohort teams, sent them their milestone documents and asking to schedule a meeting within the next week to go over them. I have a reminder set on the emails to check in a week from today.

@whenbellstoll Mind posting your status in here?

**Comment by whenbellstoll** [comment]
I have reached out to six of the seven teams VR/ IoT cohort. The only team I haven't sent materials to yet is Veative Labs because I haven't been able to get an introductory call with them. I have completed one follow up call with Avyantra already and I'm in the process of scheduling the other follow up calls with the teams.

**Comment by justwheel** [comment]
@Nolski @whenbellstoll Are all follow-up calls scheduled? If so, could we please close this issue out and/or open new ones for following up with specific cohorts?

**Comment by Nolski** [comment]
@jwflory You can see which calls I have scheduled in a separate kan-ban board here: https://github.com/orgs/librecorps/projects/2

@whenbellstoll would you mind tracking your calls there as well so we can have a good idea of where everyone is as with regards to roadmap review?

**Comment by justwheel** [comment]
@whenbellstoll Please update this issue once you add your calls to the kanban board. Thanks!

**Comment by justwheel** [comment]
It looks like all the cohorts are added to the project board: https://github.com/orgs/librecorps/projects/2?fullscreen=true

Closing as complete. :ocean:
