### ISSUE TITLE
Develop Roadmap for AI Transparency & Ethics Plans

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#5]
# Summary

As per my arrangements with UNICEF I am to develop a set of resources, tools, and guidance documents to assist machine learning focused cohorts can develop their technology in a way that is open, responsible, and ethical.

# Outcome

A document with my plans in priority order of which tasks I would like to complete.

**Comment by Nolski** [comment]
Some items discussed earlier copied in below...


Here's a couple of ideas I've had in no particular order:


## Data Schema document

A lot of AI focused products are hesitant about releasing their data. Personally, I think we should encourage this in a way that's responsible.

The OCHA Humanitarian Data Exchange has some guidelines on identifying [privacy risk to data sets](https://centre.humdata.org/three-ways-to-share-data-on-hdx/) but it's fairly vague. I reached out via email to see if they have additional guidance on how to determine whether a dataset should be public or private. They also have a little overview on [using metadata to describe datasets](https://centre.humdata.org/providing-metadata-for-your-datasets-on-hdx/)

There was a paper written on this as well: https://arxiv.org/abs/1803.09010

## Machine Learning Model Card Template

This stems from my talks with MacroEyes and Har Zindagi. They both are wary about releasing their machine learning models as they might be used improperly or not understood correctly. I think we could really provide a useful resource that hasn't been used beyond more than one project yet.

I was reading a white paper a while back which [researched this quite a bit](https://arxiv.org/abs/1810.03993). Perhaps we could also adapt the [publiccode.yml](https://github.com/publiccodenet/publiccode.yml/) document created by the public code network?

## The Perfect README Template

A lot of companies have asked for guidance on how to write good documentation. I think this is a quick and easy way to start delivering that guidance. We can expand from here.

This would be just a broad outline for a good README with all of the proper bits prefilled in. Some existing resources for this from a quick google search below:

 - https://www.makeareadme.com/
 - https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
 - https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

The roadmap exists as a template on our resources site: https://librecorps.github.io/resources/ai/milestone-roadmap/

Closing as complete. :ocean:
