### ISSUE TITLE
Data Responsibility & Sharing Guidelines

### ISSUE THREAD

**Issue by Nolski** [librecorps/tasks#6]
# Summary

Many of our AI focused cohorts are unsure as to how/whether they should release their training datasets along-side their machine learning code.

# Details

The UN OCHA has provided great guidance on releasing data, determining sensitivity, etc. The main guidance document can be found here:

https://centre.humdata.org/wp-content/uploads/2019/03/OCHA-DR-Guidelines-working-draft-032019.pdf

I have contacts at [HDX](https://data.humdata.org/) which might serve as a the perfect platform to release their data on.

# Outcome

An initial document or perhaps roadmap template for assessing & releasing a data set online.

**Comment by Nolski** [comment]
UNICEF has shown interest in their mentors assigning a number of "homework" assignments. Below is a few ideas of some assignments which can be done.

## Homework Assignments

### Phase 1

**[Data Ecosystem Map](https://docs.google.com/document/d/18Zg2JwUDJajVDX5VU0vMijL-c9yfumeAUYDc7rgC4iQ/edit#)**: This is to document where their data is coming from, what's using it, stakeholders, etc. The benefit here is not just helping organize how data collection will work in production but also projecting partnerships which may need to be formed in the future.

**[Information Sharing Protocol](https://docs.google.com/document/d/1MISHbWU7KGo4Z4AR-b222f6uXrtpQ-GJiJemGYoL--E/edit#)**: This document is all about conducting an initial assessment of the sensitivity of information you are collecting, who you want to share it with, and how. It's fairly well thought out but is worth a review and potentially some edits. If you are in the EU, it might just be better to do a [Data Protection Impact Assessment](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/data-protection-impact-assessments-dpias/what-is-a-dpia/)

### Phase 2

**[Determine Dataset Structure](https://humanitarian.atlassian.net/wiki/spaces/imtoolbox/pages/61734950/File+and+Dataset+Management)**: As you create new data sets, update them, and remove old datasets, you should follow a easy to follow protocol for keeping track of your various data sets as they're updated and deprecated.

**[]()**:

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

@Nolski Do you want to close this one out or is there anything we could add to the Resources site here?
