### ISSUE TITLE
Export AI ethics FOSDEM brainstorming into outline format

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#8]
# Summary

Export brainstorming notes / ideas into easy-to-read outline format

# Background

Our brainstorming notes are in a [shared Google Doc](https://docs.google.com/document/d/1vPuCyJR_3tukz8h7NcfCrGI82NC4Umb2uT10TejCDhc/edit?usp=sharing). We received a few rounds of feedback on our core ideas and thoughts. Now, we are in a position to frame them into an outline for the FOSDEM talk.

# Details

1. Review _Questions to ask_ section in Google Doc as a starting point
2. Create a new Google Doc in the shared folder with **only** outline and maybe abstract
3. Start expanding feedback loops more widely on our more polished ideas

# Outcome

Enable us to receive targeted feedback on our main ideas without overwhelming someone with the full contents of our brainstorming document

**Comment by Nolski** [comment]
In the shared google doc, we have an abstract, and talk overview which matches what's in the presentation.
