### ISSUE TITLE
Create spreadsheet of all public repositories / resources for all UNICEF IF cohort teams

### ISSUE THREAD

**Issue by justwheel** [librecorps/tasks#9]
# Summary

Create a shared spreadsheet with URLs for where each team is maintaining their open source project and portfolio

# Background

Each UNICEF Innovation Fund (IF) cohort uses different git forges or project-hosting tools for their projects. There is not a single resource to look at to find where each team is doing their open source development.

Our task is to help the UNICEF IF managers monitor progress of each cohort and help make the open source efforts of each cohort easier to measure and track. This also helps us because it gives us a resource to use when we want to check in on a project or if a cohort asks us for help (i.e. we can find out where their open source activity is).

# Details

This will be an iterative process and may take a month to make it a comprehensive resource. I suggest this approach:

1. Create Google Form survey with questions for each cohort that ask:
  * List all public repositories
  * Explain the role of each repository in their project (i.e. front-end? back-end? blockchain component? plug-in for another FOSS project?)
2. Send out to each cohort + UNICEF IF managers
3. Follow up with specific teams to fill the form where necessary

# Outcome

* Easier to locate open source progress and activity of a UNICEF IF cohort
* Assists UNICEF IF managers in monitoring cohort activity (separate from the work we are doing)
* Less confusion over where open source development is done, if it is being done

---

_Migrated from FOSSRIT/tasks#92._

**Comment by Nolski** [comment]
UNICEF maintains one. You can find a copy of it here: https://drive.google.com/open?id=1DByeQjLOfL3zbi0fX3JKc9plAhGu1pIrJV3HgpR3gRk

**Comment by justwheel** [comment]
@Nolski The spreadsheet provided by UNICEF is a diagnostic matrix, but it does not indicate a clear status for each team (not without digging into the details). I believe what @itprofjacobs envisioned was a spreadsheet that, at a glance, communicates overall rubric completion status for each cohort (preferably with color). This creates a feedback loop to UNICEF on how each cohort is doing on the principles we established as essential.

So, I think we can do better: sort of a summary of our wiki pages in spreadsheet form. What do you think? It is tedious but yields a positive net impact on our UNICEF contract. It gives a short-term operational benefit to Innovation Fund staff for measuring cohort progress on open source criteria. We can maintain the spreadsheet for the duration of our contract time working with each cohort.

**Comment by Nolski** [comment]
For sure! Let's keep this open then and maybe we can use some of the content in that UNICEF matrix if it proves useful.

**Comment by justwheel** [comment]
It actually looks like @whenbellstoll already worked on some of this, but it could be updated:

* [High Level Team Rubric](https://docs.google.com/spreadsheets/d/1nVUn7r0bE0RlyazwpkyKGffDqyuhx0IBFUTt0GnPgwI/edit?usp=sharing) (template?)
* [High Level Team Evaluations](https://docs.google.com/spreadsheets/d/1jfWrgw_cgxOobrO8Wy4fTm2S9hILO-4QqXYBrZPH5pc/edit?usp=sharing) (specific to our UNICEF cohorts?)

Maybe closing this issue actually means updating the second spreadsheet based on current data / statuses. A handy way to better automate the individual rubrics to the high-level rubrics might be to "link" some cells together, so changing them in one spreadsheet also changes them in another. I've done this before, but I forget how to do it…

We could have an Excel spreadsheet design conversation if it is warranted. :stuck_out_tongue_closed_eyes: I would like a time box on this task from @itprofjacobs.

**Comment by Nolski** [comment]
Can be found here: https://docs.google.com/spreadsheets/d/1OfRh6lu63ygi6wdyLLT485M4O96JwNCUnPsfCvlQ7_Y/edit?usp=sharing
